# Generated by Django 4.2.14 on 2024-09-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_topics_article_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reads_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
