# Generated by Django 4.2.14 on 2024-09-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_reads_count_article_views_count'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='articles_article',
        ),
    ]
