# Generated by Django 4.2.14 on 2024-09-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
