# Generated by Django 4.2.14 on 2024-09-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_options_alter_article_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
